# Site
repository: sproogen/moderm-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Holger Frydrych
title: Senior Consultant
email: holger@frydrych.org
website: www.frydrych.org

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  fholger
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: hfrydrych
xing_username: Holger_Frydrych
# pinterest_username: jekyll
youtube_username: "@fholger"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Half-Life 2 VR
#  icon: fas fa-globe
#  url: https://halflife2vr.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

include:
  - _pages

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Holger and I am a senior developer from Munich focussing on backend development.
  I am well versed in both the Java and .NET ecosystems and also have experience with Cloud
  and Kubernetes deployments.
  
  My true passion, though, is Virtual Reality and 3D rendering. In my free time I work on
  porting classic games to VR and other VR-related projects. C++ and Rust are my weapons of choice.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "Far Cry VR"
        link: farcryvr.de
        quote: >
          Welcome to Cabatu!
        description: | # this will include new lines to allow paragraphs
          Far Cry VR transforms the classic 2004 shooter into a full virtual reality experience with motion controls.

          With the help of the Far Cry Mod SDK, Far Cry VR is a total conversion of the game to make it
          a native VR experience. Full stereoscopic VR rendering combined with motion controller support
          lets players experience Jack Carver's visit to Cabatu from a whole new perspective.
          
          Built on the Far Cry Mod SDK and using OpenVR and a customized dxvk build to implement
          the VR rendering.
      - layout: top-middle
        title: "Half-Life 2: VR"
        link: halflife2vr.com
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Rise and shine, Mr Freeman. Rise and ... shine.
        description: | # this will include new lines to allow paragraphs
          Half Life 2: VR is a third-party modification of the 2004 PC gaming classic by Valve Software, which adds full Virtual Reality support to the original game.

          The project was originally started over a decade ago in the early days of Oculus.
          It successfully passed Steam greenlight in 2017, but then ran into trouble and was
          all but abandoned. I joined the project in July 2021 as part of an influx of new
          team members to revive it and finally get it out of the door. As the lead developer,
          I made sure to keep the project focussed on the essentials and slowly transform it
          into a playable and enjoyable experience. The project entered a private beta test phase
          in May 2022 and is launching a public beta in September 2022 on Steam.
          
          Built on the Source 2013 SDK and using OpenVR and a customized dxvk build to implement
          the VR rendering.

      - layout: top-middle
        title: The Dark Mod VR
        link: github.com/fholger/thedarkmodvr
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          The Dark Mod is a free community-developed stealth game in the spirit of the Thief series.
          I have created a VR adaptation that currently allows the game to be played as a seated
          keyboard+mouse experience in virtual reality, with motion controller support in the works.
          In the process, I have contributed many improvements to the game's renderer to make performance
          meet the needs of VR rendering. Working on this project has taught me most of what I know about
          3D rendering and VR, specifically knowledge in OpenGL, OpenVR and OpenXR.
      - layout: top-middle
        title: VR Performance Toolkit
        link: github.com/fholger/vrperfkit
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This tool can inject upscaling and fixed foveated rendering into existing VR games, giving
          users tools to improve rendering performance with an acceptable loss of visual fidelity.
          The tool works by injecting into D3D11 and VR render calls.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TNG Technology Consulting
        link: tngtech.com
        # link_text: boringcompany.com
        sub_title: Senior (since 2018) Software Consultant
        caption: April 2016 - Present
        quote: >
          We solve hard IT problems.
        description: | # this will include new lines to allow paragraphs
          TNG is a value-based consulting partnership focused on high end information technology.
          I have worked and consulted on several projects for our clients. These projects
          include: 
          - big data processing in privacy-compliant ways on AWS cloud infrastructure and K8s with Flink and Akka
          - modernizing a legacy client-facing desktop application and bringing it into the cloud as SaaS
          - building a modern web application with .NET, ASP.NET Core and Typescript/React
      - layout: left
        title: Technische Universität Darmstadt
        link: www.tu-darmstadt.de
        sub_title: Research assistant
        caption: 2011 - 2016
        description: | # this will include new lines to allow paragraphs
          Doing research and completing my PhD in the field of theoretical quantum information
          theory.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TU Darmstadt
        caption: 2011 - 2015
        sub_title: PhD Physics
        description: | # this will include new lines to allow paragraphs
          Research in theoretical physics with a focus on quantum information and quantum cryptography.
          
          Title of PhD thesis: "Advanced dynamical decoupling strategies for simulating Hamiltonian interactions"

  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #    - Rock climbing
  #    - Gaming
  #    - Knitting
  #    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #    Look at this cool image  
  #    ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: '<a href="/impressum/">Impressum</a> - <a href="/datenschutz/">Datenschutz</a>'

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
